ERROR - 2024-11-16 01:07:49 --> Failed to update book
ERROR - 2024-11-16 01:08:43 --> Failed to update book
ERROR - 2024-11-16 01:08:52 --> Failed to update book
ERROR - 2024-11-16 01:14:06 --> Failed to update book
ERROR - 2024-11-16 01:15:47 --> Failed to update book
ERROR - 2024-11-16 05:33:50 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\library_system\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\library_system\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tr...', 0)
#1 C:\laragon\www\library_system\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tr...')
#2 C:\laragon\www\library_system\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tr...')
#3 C:\laragon\www\library_system\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tr...', Array, false)
#4 C:\laragon\www\library_system\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\library_system\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\library_system\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\library_system\app\Controllers\TransactionController.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\library_system\system\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
#9 C:\laragon\www\library_system\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
#10 C:\laragon\www\library_system\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\library_system\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\library_system\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\library_system\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-11-16 05:33:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: transaction/borrow]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-16 05:33:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'3\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:50\', \'2024-11-16 05:33:50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'3\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:50\', \'2024-11-16 05:33:50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-16 05:33:50 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'3\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:50\', \'2024-11-16 05:33:50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'3\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:50\', \'2024-11-16 05:33:50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'3\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:50\', \'2024-11-16 05:33:50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-11-16 05:33:56 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\laragon\www\library_system\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\library_system\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `tr...', 0)
#1 C:\laragon\www\library_system\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tr...')
#2 C:\laragon\www\library_system\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tr...')
#3 C:\laragon\www\library_system\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tr...', Array, false)
#4 C:\laragon\www\library_system\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\library_system\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\library_system\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\library_system\app\Controllers\TransactionController.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\library_system\system\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
#9 C:\laragon\www\library_system\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
#10 C:\laragon\www\library_system\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\library_system\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\library_system\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\library_system\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-11-16 05:33:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: transaction/borrow]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-16 05:33:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'4\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:56\', \'2024-11-16 05:33:56\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'4\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:56\', \'2024-11-16 05:33:56\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-11-16 05:33:56 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'4\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:56\', \'2024-11-16 05:33:56\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'4\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:56\', \'2024-11-16 05:33:56\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (\'4\', \'20\', \'2024-11-16\', \'borrowed\', \'2024-11-16 05:33:56\', \'2024-11-16 05:33:56\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `transactions` (`book_id`, `user_id`, `borrow_date`, `status`, `created_at`, `updated_at`) VALUES (:book_id:, :user_id:, :borrow_date:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\TransactionController.php(51): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\TransactionController->borrow()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TransactionController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(57): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
